### ISSUE TITLE
Add increment option.

### ISSUE THREAD

**Issue by DylanPiercey** [lukechilds/keyv#12]
Both mongodb and redis support a way increment variables directly. It would be nice to have something similar here. Specifically I am wanting to use keyv to implement a rate limiter but without increment it's impossible to do so. 

May be out of scope for the module but I thought it'd be cool.

---

Also this module is legit. Thanks for making it :).

**Comment by lukechilds** [comment]
Thanks for the idea but yeah, that's definitely out of scope. I really wanna keep this simple and focused on key-value API compatibility across backends.

**Comment by AdamPflug** [comment]
I also need this functionality (actually for a similar reason) and wanted to confirm it's out of scope before I go write my own package to do this. Unfortunately you can't just build this functionality on top of keyv because you need to talk to the stores in a different way for this to be an atomic operation (where you don't get lost updates with concurrent requests and separate `.get` and `.set` calls).

That said, all the stores I know about that you support are either synchronous (e.g. Map(), quick-lru) or support an atomic increment mechanism (memcached, redis, mongo, sql, dynamodb) - so it's technically possible but does extend outside of the Map API spec.

**Comment by lukechilds** [comment]
>I also need this functionality (actually for a similar reason) and wanted to confirm it's out of scope before I go write my own package to do this.

Yeah I think so, but thanks for checking back.

>Unfortunately you can't just build this functionality on top of keyv

Why not fork Keyv?

If the changes are relatively simple and it works well across all storage adapters, I might be open to merging it in.

If it's too complex or doesn't work reliably enough across storage adapters, you'll still have your own fully working package for your own needs.
