### ISSUE TITLE
Keyv Not Writing Value

### ISSUE THREAD

**Issue by TheCuteFoxxy** [lukechilds/keyv#121]
When trying to write a value from an undefined `get`. Keyv fails to write the value to the database.

Code: https://pastebin.com/ZJG9qYrp

Screenshot of What The Database Shows: https://cdn.foxybots.xyz/xhfvzf

I have been trying different ways of setting up Keyv to write this for days now (and its only in this scenario I have an issue, my other commands work fine with a similar setup of the if undefined/null)

**Comment by noahjsmyth** [comment]
I have the same problem in a similar setup to yours.

**Comment by Kikobeats** [comment]
write `undefined` is the same than don't write the value

https://github.com/lukechilds/keyv-redis/blob/master/src/index.js#L36

**Comment by Hamster-0001** [comment]
@Kikobeats Can you clarify? The issue only occurs in this instance, the undefined should only occur if the value does not already exist. Which is the reason I am writing a set value for the key. Which normally would overwrite the undefined.

I know this should work as I have done it in other instances, which is why I am here.

**Comment by Hamster-0001** [comment]
Issue is persistent with a different variation as well (Even tried doing a fresh .set() without checking for undefined). When hardcoding the key and value, it writes normally.

**Comment by Hamster-0001** [comment]
Bumping to prevent closure.

**Comment by TheCuteFoxxy** [comment]
Considering no one is able to answer or assist, closing as stale.
