### ISSUE TITLE
Add multilayer support

### ISSUE THREAD

**Issue by Kikobeats** [lukechilds/keyv#28]
The idea is provide more than one layer support as fallback.

Similar to cache L1 and L2 approach.
https://people.csail.mit.edu/sanchez/papers/2016.model.hpca.pdf

Just an example aproximation using redis and memory implementation.

`get` operations:
- first try to get the value from redis instance.
- it it fails, try to find the value in the memory implementation.
- under memory hit, move the key to redis.

`set` operations:
- if redis have a free slot, use it.
- if redis doesn't have a free slot but the slot it's available on memory, use it.
- otherwise, remove the oldest reference entry at memory implementation.

**Comment by lukechilds** [comment]
Thanks for taking the time to put your thoughts together so clearly. This is actually something I considered implementing when writing Keyv but decided against for two reasons:

**1. Keyv works well with multiple nodes backed by a single store.**

If you throw multiple cache layers into the mix it gets very complicated. If you have two Node.js servers connected to the same Redis instance with an in memory cache as the first layer, it's very easy to end up with data inconsistencies.

You need to make sure writes to server 1's memory are instantly reflected in Redis and server 2s memory, otherwise reads from server 2 will be inconsistent with reads from server 1.

**2. Keyv is designed to be a consistent interface for key-value storage across multiple backends.**

 That's it. I wanna keep it simple. Any additional functionality should be implemented as a separate module that uses Keyv under the hood to support multiple backends.


So for those two reasons I'm against adding this directly to Keyv. However I think the functionality you describe would be very useful to a lot of people. If you think of a good solution to problem 1, I'd encourage you to write your own module implementing your solution on top of Keyv. And let me know if you do, I'd love to check it out!

**Comment by Kikobeats** [comment]
Thanks of the reply 😄
